### ISSUE TITLE
Enhancement: support mp4 files

### ISSUE THREAD

**Issue by violetknights** [dodecastudio/craft-lightbox#1]
Heya,

I'm new to CraftCMS & its plugin system. However, I somehow managed to get it up & tried your plugin out. It works very well with images. I know this is an out of scope question. Is it difficult to support media files (e.g. MP4) in the light box?

Here is a short video recording I tried the plugin with an small MP4 file:

https://user-images.githubusercontent.com/1762174/179391727-62b8d6b2-95a2-48af-b5d9-7a3a1c47822e.mov

**Comment by tomkiss** [comment]
Hi @violetknights,

Yes, there is some very basic functionality for unsupported file types - just displaying a link to the file (rather than doing nothing).

MP4 files have good browser support and it would straightforward to implement - so I'll keep this issue open. If I find myself with some time I'll add support (I'd also like to do this slowly over time with other filetypes too).

**Comment by violetknights** [comment]
Thanks Tom. I updated & it works.

![image](https://user-images.githubusercontent.com/1762174/198945615-b1b99e24-89ce-48c4-8456-e0029e47bcfd.png)
